### ISSUE TITLE
Error message: Assertion Failed: 'data-adapter' is not a recognized type

### ISSUE THREAD

**Issue by broerse** [emberjs/ember-inspector#1111]
Clicking on "Data" in the inspector does not work anymore for the Bloggr example at https://bloggr.exmer.com/ . It always worked fine.
 
VM36:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Assertion Failed: 'data-adapter' is not a recognized type
Stack trace: Error: Assertion Failed: 'data-adapter' is not a recognized type
    at https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:8112:85
    at e._definitiveCollection (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:8109:19)
    at e.identify (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:8106:361)
    at e.resolve (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:8107:246)
    at n.resolve (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:10184:44)
    at n.resolve (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:10165:240)
    at n [as resolve] (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:3300:9)
    at https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:1633:27
    at e.resolve (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:1636:10)
    at e.resolve (https://bloggr.exmer.com/assets/vendor-53fbb4a694da8b076918420d066804bf.js:1637:64)

**Comment by rwwagner90** [comment]
@broerse what version of inspector?

**Comment by broerse** [comment]
@rwwagner90  Version 3.12.5

**Comment by paddor** [comment]
I have the same issue with Ember Inspector 4.11.0 and 4.12.1-alpha.2024.7.18+75b6399

Ember: 5.4.1
Ember-Data: 5.3.8
