### ISSUE TITLE
Unable to detect ember sites, inspect elements

### ISSUE THREAD

**Issue by LukeClancy** [emberjs/ember-inspector#1164]
**Describe the bug**
Unable to detect ember sites sometimes (look at top right):
![image](https://user-images.githubusercontent.com/15352748/77965108-339f6880-7295-11ea-8546-096e676934b4.png)

Other times detection works, but (right clicking page) -> (inspect ember component) does not do anything:

![image](https://user-images.githubusercontent.com/15352748/77965691-685fef80-7296-11ea-91ba-8c1f8b631baf.png)

**To Reproduce**
1. Go to Chrome on linux
2. Install ember-inspection
3. attempt to use
4. See issue

**Environment**
linux Pop!-OS 19.10 x86_64
kernel 5.3.0-7642-generic

**Additional context**
- Usually use firefox. Chrome is not default browser, could that be an issue?

**Comment by rwwagner90** [comment]
@chancancode @nummi do we want to support all Linux distros? I think an infinite support matrix could get hairy. I have never heard of `linux Pop!`, so I am not sure how to debug.

**Comment by nummi** [comment]
Is this really a system bug? I feel like this would be scoped to the browser.

**Comment by nummi** [comment]
Emberjs.com:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/3692/78504879-945ef300-7724-11ea-9de2-d5f644ffb7d7.png">

Neither of these work for me:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/3692/78504909-c1130a80-7724-11ea-8dce-3ffa4a880754.png">

**Comment by rwwagner90** [comment]
@nummi `inspect ember component` has never really worked. It works if you have inspector open already, but does not open inspector for you anymore, for whatever reason.

As for the message about running Ember.js or not, I am unsure what detects that, but inspector still works, despite the message.

**Comment by chancancode** [comment]
I agree it’s unlikely to do with the OS and they are kind of “known” issues. If we don’t already have one lets make a stand-alone issue for each of these bugs. Given time I think we know how to fix them.

**Comment by steffansluis** [comment]
Having potentially the same problem? I built the extension manually and when loading it got the following error:
```
content-script.js:47 Uncaught Error: Extension context invalidated.
    at listenToEmberDebugPort (content-script.js:47:20)
    at content-script.js:30:7
listenToEmberDebugPort @ content-script.js:47
(anonymous) @ content-script.js:30
postMessage (async)
(anonymous) @ VM318:10127
(anonymous) @ VM318:10267
(anonymous) @ VM318:10269
Promise.then (async)
loadEmberDebugInWebpage @ VM318:21
(anonymous) @ VM318:10271
```

**Comment by patricklx** [comment]
this might be related to https://github.com/emberjs/ember-inspector/pull/2051 where it sometimes failed to detect the ember app

**Comment by RobbieTheWagner** [comment]
Cleaning up some issues, and going to close this for now. If you are still having issues, please let us know!
