### ISSUE TITLE
Model is not defined

### ISSUE THREAD

**Issue by beastmst** [emberjs/ember-inspector#1194]
when run  ember 3.12.2, the inspector said the model not defined

currently the project is running in pod mode.. only is the model is not..
all model files still in the app/model forlder.. 
and other than that, other files is in the pod subfolrder

VM77:103 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Model is not defined
Stack trace: ReferenceError: Model is not defined
    at Module.callback (http://localhost:4200/assets/adtikir3v1.js:7893:18)
    at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:159161:20)
    at Class.resolveOther (http://localhost:4200/assets/vendor.js:158832:32)
    at Class.resolve (http://localhost:4200/assets/vendor.js:158892:25)
    at resolve (http://localhost:4200/assets/vendor.js:18121:36)
    at Registry.resolve (http://localhost:4200/assets/vendor.js:17661:21)
    at Registry.resolve (http://localhost:4200/assets/vendor.js:17664:33)
    at factoryFor (http://localhost:4200/assets/vendor.js:17221:38)

**Comment by RobbieTheWagner** [comment]
Apologies for never responding to this! This _looks_ like maybe there was a missing import in your app?
