### ISSUE TITLE
CI Failures on Ember Canary

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-inspector#1298]
CI is failing currently for `ember try:one ember-canary` with the following error:

```
not ok 9 Chrome 84.0 - [41 ms] - Ember Debug - Object Inspector: An ES6 Class is correctly transformed into an inspection hash
    ---
        actual: >
            null
        stack: >
            TypeError: tag[COMPUTE] is not a function
                at valueForTag (http://localhost:7357/testing/assets/vendor.js:56470:24)
                at http://localhost:7357/testing/ember_debug.js:4795:34
                at Array.forEach (<anonymous>)
                at http://localhost:7357/testing/ember_debug.js:4770:24
                at Array.forEach (<anonymous>)
                at calculateCPs (http://localhost:7357/testing/ember_debug.js:4769:18)
                at Class.mixinsForObject (http://localhost:7357/testing/ember_debug.js:4451:7)
                at Class.sendObject (http://localhost:7357/testing/ember_debug.js:4254:26)
                at http://localhost:7357/testing/assets/tests.js:5678:35
                at _callee29$ (http://localhost:7357/testing/assets/tests.js:5466:22)
        message: >
            Promise rejected during "An ES6 Class is correctly transformed into an inspection hash": tag[COMPUTE] is not a function
```

The last passing ember-canary scenario that I see is from [2020-08-01](https://github.com/emberjs/ember-inspector/runs/934084268?check_suite_focus=true) and the first failure is from [2020-08-03](https://github.com/emberjs/ember-inspector/runs/938599750?check_suite_focus=true).

**Comment by rwjblue** [comment]
Based on a conversation with @pzuraq I think the issue is that the `valueForTag` method in GlimmerVM here:

https://github.com/glimmerjs/glimmer-vm/blob/v0.56.0/packages/@glimmer/validator/lib/validators.ts#L39-L49

No longer guards for the incoming argument _not_ being a tag, which it used to do:

https://github.com/glimmerjs/glimmer-vm/blob/v0.55.1/packages/@glimmer/validator/lib/validators.ts#L39-L55

The main change here was landed in https://github.com/glimmerjs/glimmer-vm/pull/1108.

**Comment by rwjblue** [comment]
I think we need to ensure that we call `valueForTag` with an actual `Tag` instance in these two spots:

https://github.com/emberjs/ember-inspector/blob/50db91b7bd26b12098cae774a307208fe0a47d75/ember_debug/object-inspector.js#L287-L292

https://github.com/emberjs/ember-inspector/blob/50db91b7bd26b12098cae774a307208fe0a47d75/ember_debug/object-inspector.js#L1096

**Comment by rwjblue** [comment]
On a quick skim it seems that the general API that we are using is fairly fundamentally wrong (`valueForTag` which is what this is using, is always going to be passed two args but the function doesn't tag two arguments...)
