### ISSUE TITLE
Routes tab does not show any existing route

### ISSUE THREAD

**Issue by Andrik264** [emberjs/ember-inspector#1806]
**Describe the bug**
Ember inspector does not show any existing route on 'Routes' page.

**To Reproduce**
1. Go to 'Ember-inspector'
2. Click on 'Routes'
3. See error

**Expected behavior**
The list of all existing routes.

**Screenshots**
![image](https://user-images.githubusercontent.com/69592267/142582776-f5020113-75cd-4865-b571-5c51e1126979.png)
![image](https://user-images.githubusercontent.com/69592267/142582836-d9acb714-db47-4221-bdce-13838acc96f3.png)

**Environment**
Browser: Google Chrome Version 96.0.4664.55 (Official Build) (x86_64).
Ember-cli: 3.27.0.
Ember-inspecor: 
- version 4.5.3;
- Allow access to file URLs - true;
- Site access - on all sites.

**Additional context**
The problem appeared more then month ago.
An error from console:
```
VM173:91 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: decorator is not a function
Stack trace: TypeError: decorator is not a function
    at https://localhost:4200/assets/ember-app.js:65354:412
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (https://localhost:4200/assets/ember-app.js:65354:369)
    at Module.callback (https://localhost:4200/assets/ember-app.js:65382:37)
    at Module.exports (https://localhost:4200/assets/vendor.js:118:32)
    at requireModule (https://localhost:4200/assets/vendor.js:39:18)
    at Class._extractDefaultExport (https://localhost:4200/assets/vendor.js:227856:20)
    at Class.resolveOther (https://localhost:4200/assets/vendor.js:227540:32)
    at Class.resolve (https://localhost:4200/assets/vendor.js:227598:25)
    at _resolve (https://localhost:4200/assets/vendor.js:19951:36)
```

**Comment by rwwagner90** [comment]
@Andrik264 is there a site we can use to reproduce this?

**Comment by Andrik264** [comment]
@rwwagner90 
It's a closed website. I can only provide you credentials for our stage server where this bug is also reproducing.
Can I write you somewhere in private messages?

**Comment by rwwagner90** [comment]
@Andrik264 yes, are you on the Ember Discord? I am rwwagner90 on there too

**Comment by Andrik264** [comment]
@rwwagner90 Writed you in pm on Discord. Check it
