### ISSUE TITLE
Error while trying to build (`glob` has no method `hasMagic`)

### ISSUE THREAD

**Issue by huafu** [emberjs/ember-inspector#325]
I just cloned the repo from `master` and tried to build it from source since I need the fix for `EXTEND_PROTOTYPES=false` #316.
After cloning and installing npm and bower packages, I tried to build following the explanations in README but I am experiencing this issue:

```
> $ npm run build:chrome
> ember-inspector@1.8.0 build:chrome /Users/huafu/Documents/tools/ember-inspector
> EMBER_DIST=chrome ember build --output-path dist_chrome/panes

version: 0.1.12
Cleanup error.
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at Function.rimrafSync [as sync] (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)
    at ConfigLoader.CachingWriter.cleanup (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:114:10)
    at cleanupTree (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
    at /Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli/node_modules/promise-map-series/index.js:11:14
    at $$$internal$$tryCatch (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at Object.$$rsvp$asap$$flush [as _onImmediate] (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
Build failed.
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at rimraf (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/Users/huafu/Documents/tools/ember-inspector/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:chrome"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! ember-inspector@1.8.0 build:chrome: `EMBER_DIST=chrome ember build --output-path dist_chrome/panes`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ember-inspector@1.8.0 build:chrome script 'EMBER_DIST=chrome ember build --output-path dist_chrome/panes'.
npm ERR! This is most likely a problem with the ember-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     EMBER_DIST=chrome ember build --output-path dist_chrome/panes
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-inspector
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/huafu/Documents/tools/ember-inspector/npm-debug.log
```

FYI:
```
> $ ember --version
version: 0.1.12
node: 0.10.36
npm: 2.1.8
```

**Comment by huafu** [comment]
I tried to fix the version of `glob` and `rimraf` as explained in emberjs/ember-cli#3486 with `npm install --save-dev glob@4.0.5 rimraf@2.2.8` but it did not change anything.

Sounds also referenced in emberjs/ember-cli#3492

**Comment by stefanpenner** [comment]
stupid npm...

**Comment by teddyzeenny** [comment]
Can you try upgrading npm? I'm on `2.7.3` and the build seems to be working.

**Comment by locks** [comment]
I'm closing this as it is unlikely to still be relevant. Feel free to reopen if that's not the case.
