### ISSUE TITLE
TypeError: Cannot read property 'firstNode' of null

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/ember-inspector#373]
Not entirely sure what caused this to happen. Currently trying to update to ember 1.11 and getting `Uncaught SyntaxError: Unexpected token u` when switching from ObjectController to Controller. I clicked on the controller from `View Tree` and then trace in console for Errors from the controller

```
VM1520:94 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'firstNode' of null
Stack trace: TypeError: Cannot read property 'firstNode' of null
    at getViewRange (.../scripts/libs/1.11/ember.debug.js:38978:37)
    at getViewBoundingClientRect (.../scripts/libs/1.11/ember.debug.js:39011:17)
    at Ember.Object.extend.highlightView (<anonymous>:3720:16)
    at Ember.Object.extend.previewLayer (<anonymous>:3895:12)
    at Ember.Object.extend.messages.previewLayer (<anonymous>:3360:16)
    at Object.apply (.../scripts/libs/1.11/ember.debug.js:18038:25)
    at Object.sendEvent (.../scripts/libs/1.11/ember.debug.js:12379:17)
    at exports.default.mixin.Mixin.create.trigger (.../scripts/libs/1.11/ember.debug.js:29705:14)
    at <anonymous>:2666:14
    at null.<anonymous> (<anonymous>:2696:18)
```

Edit: Potentially relevant

```
Ember Inspector
1.8.0
Ember
1.11.0
Ember Data
1.0.0-beta.18
jQuery
2.0.3
```

**Comment by rwjblue** [comment]
Complete guess, but whenever I see `Unexpected token u` it is generally a `JSON.parse("undefined")`...

**Comment by Frozenfire92** [comment]
That was it, thank you
