### ISSUE TITLE
Ember Inspector has errored

### ISSUE THREAD

**Issue by gonvaled** [emberjs/ember-inspector#403]
```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 't' of undefined
Stack trace: TypeError: Cannot read property 't' of undefined
    at http://localhost:4200/assets/app.js:2492:38
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:4200/assets/vendor.js:58819:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:58561:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:27982:20)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15151:35)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:14991:23)
    at resolve (http://localhost:4200/assets/vendor.js:12663:29)
```

The error happens because I forgot to install `ember-i18n`, and while inspecting (?) this code, ember inspector crashes:

```
import Ember from 'ember';

var trans = Ember.I18n.t;

...
```

This is definitely an error in my code, but still ember inspector shouldn't crash.

This is my setup:

```
DEBUG: -------------------------------
ember.debug.js:4888 DEBUG: Ember      : 1.12.0
ember.debug.js:4888 DEBUG: Ember Data : 1.0.0-beta.18
ember.debug.js:4888 DEBUG: jQuery     : 1.11.3
ember.debug.js:4888 DEBUG: -------------------------------
```

And:

```
» ember -v
version: 0.2.7
node: 0.12.2
npm: 2.11.0
```

**Comment by teddyzeenny** [comment]
> while inspecting (?) this code

What specific action did you do in the inspector that triggered the error?

**Comment by teddyzeenny** [comment]
ping @gonvaled

**Comment by locks** [comment]
Closing this due to lack of response from @gonvaled. Please reopen if you can provide the necessary information.
