### ISSUE TITLE
Build Error: The Babel plugin uses the new `.rebuild` API

### ISSUE THREAD

**Issue by RyanHirsch** [emberjs/ember-inspector#407]
Checking out from master and following the instructions to do a `npm run build` causes the following error
```
Build failed.
The Babel plugin uses the new `.rebuild` API. Upgrade to Broccoli 0.14.0 or newer to use this plugin. More info: https://github.com/broccolijs/broccoli/blob/master/docs/new-rebuild-api.md
Error: The Babel plugin uses the new `.rebuild` API. Upgrade to Broccoli 0.14.0 or newer to use this plugin. More info: https://github.com/broccolijs/broccoli/blob/master/docs/new-rebuild-api.md
  at readAndReturnNodeFor (C:\projects\ember-inspector\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:70:15)
  at C:\projects\ember-inspector\node_modules\ember-cli\node_modules\broccoli\lib\builder.js:93:24
  at lib$rsvp$$internal$$tryCatch (C:\projects\ember-inspector\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (C:\projects\ember-inspector\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:501:17)
  at C:\projects\ember-inspector\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1095:13
  at lib$rsvp$asap$$flush (C:\projects\ember-inspector\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1290:9)
  at process._tickCallback (node.js:340:13)
```

**Comment by kirkportas** [comment]
I'm seeing the same issue and local+global reinstalls haven't resolved this.

Going back to commit 376234c does allow for a successful ```npm run build```, but the dist_chrome dir is missing the panes/ directory and thus isn't a valid extension. 

The skeleton_chrome folder in the repo is also missing the panes/ directory. https://github.com/emberjs/ember-inspector/tree/master/skeleton_chrome

Is there a known working version that builds into a chrome extension?

**Comment by mehulkar** [comment]
Getting this as well, but on ember-cli.
