### ISSUE TITLE
Ember inspector has errored

### ISSUE THREAD

**Issue by JDillon522** [emberjs/ember-inspector#420]
It was working fine and then it started dying on page load with the following:

> DEBUG: -------------------------------
DEBUG: Ember      : 1.12.1
DEBUG: Ember Data : 1.0.0-beta.19.2
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------
Ember Inspector Active
Preparing to transition from '' to 'login'
Transitioned into 'login'

>Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: (intermediate value).property(...) is not a function

>Stack trace: TypeError: (intermediate value).property(...) is not a function
    at http://localhost:9000/assets/testApp.js:2196:30
    at mod.state (http://localhost:9000/assets/vendor.js:150:29)
    at tryFinally (http://localhost:9000/assets/vendor.js:30:14)
    at requireModule (http://localhost:9000/assets/vendor.js:148:5)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:9000/assets/vendor.js:58828:20)
    at resolveOther (http://localhost:9000/assets/vendor.js:58570:32)
    at superWrapper (http://localhost:9000/assets/vendor.js:27739:20)
    at exports.default.EmberObject.default.extend.resolveController (http://localhost:9000/assets/vendor.js:15289:19)
    at exports.default.EmberObject.default.extend.resolve (http://localhost:9000/assets/vendor.js:15144:43)
    at Object.resolve [as resolver] (http://localhost:9000/assets/vendor.js:14987:23)

I came across [this issue](https://github.com/ember-cli/ember-cli/issues/3981) describing the error, but its now causing the inspector to die a terrible death.

**Comment by teddyzeenny** [comment]
Does the error still occur without the inspector active?

**Comment by JDillon522** [comment]
Oddly, no. I disabled the inspector, closed my tab, reopened it, and re-enabled it and it works fine. I'm also not getting the other console error either. This is probably just my machine :angry: 

Thanks

**Comment by teddyzeenny** [comment]
It's possible it depends on the tab that was open. Maybe the routes tab?

**Comment by JDillon522** [comment]
Ah yup, thats what did it. Just clicking on the routes kills it with the same error.

**Comment by teddyzeenny** [comment]
This probably means you have an error in one of your route files. My guess is you are using `.property` in one of your routes with prototype extensions turned off.

**Comment by teddyzeenny** [comment]
ping @JDillon522

**Comment by JDillon522** [comment]
Sorry. I lost track of this issue. I can't remember what fixed it but I do recall it was an error in one of my routes (but not a `.property()` occurrence)
