### ISSUE TITLE
Data Tab Broken

### ISSUE THREAD

**Issue by nlfurniss** [emberjs/ember-inspector#453]
When you click on the Data tab, it doesn't switch to the Data view.

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Assertion Failed: Expected hash or Mixin instance, got [object Function]
Stack trace: Error: Assertion Failed: Expected hash or Mixin instance, got [object Function]
    at new Error (native)
    at Error.EmberError (http://localhost:4443/assets/vendor.js:25339:21)
    at Object._emberMetalCore.default.assert (http://localhost:4443/assets/vendor.js:14969:13)
    at MixinPrototype.reopen (http://localhost:4443/assets/vendor.js:27884:34)
    at Function.ClassMixinProps.extend (http://localhost:4443/assets/vendor.js:47106:14)
    at http://localhost:4443/assets/voyager-web.js:63317:43
    at mod.state (http://localhost:4443/assets/vendor.js:364:29)
    at tryFinally (http://localhost:4443/assets/vendor.js:244:14)
    at requireModule (http://localhost:4443/assets/vendor.js:362:5)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:4443/assets/vendor.js:68279:20)
```

**Comment by FutoRicky** [comment]
Same thing here:
```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: describe is not defined
Stack trace: ReferenceError: describe is not defined
```

**Comment by teddyzeenny** [comment]
Thanks for reporting this. Can you please post your library versions (The inspector "Info" tab) and if you're using ember-cli or not.

Can you reproduce this issue in a jsbin or a public repo?
