### ISSUE TITLE
Attempting to inject an unknown injection: `service:globals`

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember-inspector#459]
```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Attempting to inject an unknown injection: `service:globals`
Stack trace: Error: Attempting to inject an unknown injection: `service:globals`
    at Object.Registry.validateInjections (http://localhost:4200/assets/vendor.js:12668:17)
    at instantiate (http://localhost:4200/assets/vendor.js:12027:29)
    at lookup (http://localhost:4200/assets/vendor.js:11906:17)
    at Object.Container.lookup (http://localhost:4200/assets/vendor.js:11853:14)
    at Object._emberRuntimeSystemObject.default.extend._getHandlerFunction [as getHandler] (http://localhost:4200/assets/vendor.js:38027:33)
    at buildSubTree (<anonymous>:3346:63)
    at null.<anonymous> (<anonymous>:3265:22)
    at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:24213:28)
    at Object.get (http://localhost:4200/assets/vendor.js:29322:19)
    at exports.default._emberMetalMixin.Mixin.create.get (http://localhost:4200/assets/vendor.js:43159:38)
```

Happening while trying to transition to EmberJS 2.0.

**Comment by teddyzeenny** [comment]
That happens when you open the Routes pane right? Is it possible you're injecting `service:globals` into one of your routes (when there's no `service:globals`)

**Comment by blimmer** [comment]
I define my own `service:globals` - is it possible there's a namespace conflict?

**Comment by locks** [comment]
@blimmer was there a resolution? I'm not sure there's anything to be done from the Inspector side here, please reopen if I'm mistaken!
