### ISSUE TITLE
Error message: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by Norjin** [emberjs/ember-inspector#507]
chrome dev tool shows this error after I upgrade ember to 2.3.0-beta.3 and ember-data to  2.3.0-beta.5
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'extend' of undefined
Stack trace: TypeError: Cannot read property 'extend' of undefined
    at Module.callback (http://localhost:4200/assets/app.js:801:51)
    at Module.exports (http://localhost:4200/assets/vendor.js:90:34)
    at Module.build (http://localhost:4200/assets/vendor.js:140:10)
    at findModule (http://localhost:4200/assets/vendor.js:188:9)
    at requireModule (http://localhost:4200/assets/vendor.js:175:12)
    at _extractDefaultExport (http://localhost:4200/assets/vendor.js:88275:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:88010:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:33124:22)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:16199:35)
    at resolve (http://localhost:4200/assets/vendor.js:12928:36)
    at Object.Registry.resolve (http://localhost:4200/assets/vendor.js:12468:21)

**Comment by jchonc** [comment]
Got the same error but on 2.2.0 (both Ember and Ember-Data).  I have polymorphic models, not sure if it's related.

**Comment by RyanNerd** [comment]
```
ember --version
version: 1.13.13
node: 5.9.1
npm: 2.14.10
os: linux x64
```
Same thing:

> Ember Inspector has errored.
> This is likely a bug in the inspector itself.
> You can report bugs at https://github.com/emberjs/ember-inspector.
> Error message: Cannot read property 'extend' of undefined
> Stack trace: TypeError: Cannot read property 'extend' of undefined
> ...

**Comment by teddyzeenny** [comment]
Can you post a screenshot of the "Info" tab?

**Comment by rwolffgang** [comment]
Same here, my Info tab shows:

- Ember Inspector 1.10.0
- Ember 2.4.5
- Ember Data 2.5.3
- jQuery 1.11.3

It happens when I try to access the Data tab:

> Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'extend' of undefined
Stack trace: TypeError: Cannot read property 'extend' of undefined
    at Module.callback (http://localhost:4200/assets/project-name.js:2527:34)
    at Module.exports (http://localhost:4200/assets/vendor.js:119:34)
    at Module.build (http://localhost:4200/assets/vendor.js:174:10)
    at findModule (http://localhost:4200/assets/vendor.js:223:9)
    at requireModule (http://localhost:4200/assets/vendor.js:26:12)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:109598:20)
    at Class.resolveOther (http://localhost:4200/assets/vendor.js:109333:32)
    at Class.superWrapper (http://localhost:4200/assets/vendor.js:33812:22)
    at Class.resolve (http://localhost:4200/assets/vendor.js:16480:35)
    at resolve (http://localhost:4200/assets/vendor.js:13034:36)

The section of code is:

```javascript
define('project-name/models/player', ['exports', 'ember-data'], function (exports, _emberData) {
	exports['default'] = Ember.Model.extend({ // this is line 2527
		title: _emberData['default'].attr('string', "Song Title in Model"),
```

So it looks like Ember.Model is undefined?

**Comment by rwolffgang** [comment]
A little bit embarrassing, but I just solved it myself. Of course `Ember.Model` does not exist, but `DS.Model` does. So the problem was within my own code. It's an old file of a model, that's not used anymore. Maybe someone else made a similar mistake?
