### ISSUE TITLE
emberData.default.atrr is not a function

### ISSUE THREAD

**Issue by flpms** [emberjs/ember-inspector#514]
Follow the log for a bug with ember-inspector.

```
DEBUG: -------------------------------
DEBUG: Ember      : 2.3.0
DEBUG: Ember Data : v2.3.0
DEBUG: jQuery     : 2.1.4
DEBUG: -------------------------------

Ember Inspector Active
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: _emberData.default.atrr is not a function

Stack trace: TypeError: _emberData.default.atrr is not a function
    at Module.callback (http://localhost:4200/assets/front-admin.js:264:35)
    at Module.exports (http://localhost:4200/assets/vendor.js:63:34)
    at Module.build (http://localhost:4200/assets/vendor.js:113:10)
    at findModule (http://localhost:4200/assets/vendor.js:161:9)
    at requireModule (http://localhost:4200/assets/vendor.js:148:12)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:4200/assets/vendor.js:65490:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:65222:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:31966:22)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15031:35)
    at resolve (http://localhost:4200/assets/vendor.js:11760:36)
```

**Comment by rwwagner90** [comment]
Closing this, as I have not recently seen it. Feel free to reopen if it is still an issue!
