### ISSUE TITLE
Error message: (intermediate value).property is not a function

### ISSUE THREAD

**Issue by NikkiDreams** [emberjs/ember-inspector#521]
I get this error just when clicking on Data in the left column. 
ln the other items seem to function correctly. 

This is the line of code from the model referred to in the from the stacktrace:
at Module.callback (http://nix.apps.5movez.com/access/assets/access-workout.js:11681:8)

```
 orderedQueues: (function () {
      return this.get("queues").sortBy("position");
    }).property("queues.@each.position")
```

```
DEBUG: -------------------------------
vendor.js:25892 DEBUG: Ember             : 2.3.0
vendor.js:25892 DEBUG: Ember Data        : 2.3.3
vendor.js:25892 DEBUG: jQuery            : 2.2.0
vendor.js:25892 DEBUG: Ember Simple Auth : 1.1.0-beta.1
vendor.js:25892 DEBUG: -------------------------------

Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: (intermediate value).property is not a function
Stack trace: TypeError: (intermediate value).property is not a function
    at Module.callback (http://nix.apps.5movez.com/access/assets/access-workout.js:11681:8)
    at Module.exports (http://nix.apps.5movez.com/access/assets/vendor.js:9645:34)
    at Module.build (http://nix.apps.5movez.com/access/assets/vendor.js:9695:10)
    at findModule (http://nix.apps.5movez.com/access/assets/vendor.js:9743:9)
    at requireModule (http://nix.apps.5movez.com/access/assets/vendor.js:9730:12)
    at _extractDefaultExport (http://nix.apps.5movez.com/access/assets/vendor.js:141419:20)
    at resolveOther (http://nix.apps.5movez.com/access/assets/vendor.js:141154:32)
    at superWrapper (http://nix.apps.5movez.com/access/assets/vendor.js:42178:22)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://nix.apps.5movez.com/access/assets/vendor.js:25243:35)
    at resolve (http://nix.apps.5movez.com/access/assets/vendor.js:21972:36)
```

**Comment by nikolas** [comment]
I got a similar error on https://travis-ci.org, using version 1.9.5 of the inspector on Chromium.

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: locationImplementation.formatURL is not a function
Stack trace: TypeError: locationImplementation.formatURL is not a function
    at getURL (<anonymous>:3430:36)
    at buildSubTree (<anonymous>:3376:40)
    at null.<anonymous> (<anonymous>:3269:22)
    at o.p.get (https://cdn.travis-ci.org/assets/vendor-d951d23c9566f887f857bd23a915e5e7.js:10:5736)
    at Object.a (https://cdn.travis-ci.org/assets/vendor-d951d23c9566f887f857bd23a915e5e7.js:11:9327)
    at e.default.a.Mixin.create.get (https://cdn.travis-ci.org/assets/vendor-d951d23c9566f887f857bd23a915e5e7.js:14:17974)
    at sendTree (<anonymous>:3275:28)
    at getTree (<anonymous>:3245:14)
    at Object.p [as apply] (https://cdn.travis-ci.org/assets/vendor-d951d23c9566f887f857bd23a915e5e7.js:11:25658)
    at Object.f [as sendEvent] (https://cdn.travis-ci.org/assets/vendor-d951d23c9566f887f857bd23a915e5e7.js:10:14638)
```

**Comment by teddyzeenny** [comment]
These issues look like errors in the app code not the inspector. It's possible they were labeled as "Ember Inspector errors" because the inspector was the first to evaluate the modules containing the error.

**Comment by locks** [comment]
I'm closing this because I agree with Teddy that this seems more of an application code error than an Inspector error. The `()` surrounding the function in the original post seem out of place.
Please let us know if you have any developments, thanks!
