### ISSUE TITLE
Erro when i click ViewTree and any Controller.

### ISSUE THREAD

**Issue by cristianounix** [emberjs/ember-inspector#523]
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: inspect is not defined
Stack trace: ReferenceError: inspect is not defined
    at inspectElement (<anonymous>:300:7)
    at inspectElement (<anonymous>:3640:29)
    at inspectElement (<anonymous>:3552:14)
    at Object.apply (http://app/assets/vendor.js:28645:25)
    at Object.sendEvent (http://app/assets/vendor.js:22986:17)
    at exports.default.mixin.Mixin.create.trigger (http://app/assets/vendor.js:40347:14)
    at <anonymous>:2799:16
    at .<anonymous> (<anonymous>:2829:18)
    at Object.Backburner.run (http://app/assets/vendor.js:10771:27)
    at run (http://app/assets/vendor.js:26526:27)
    at wrap (<anonymous>:2827:14)

**Comment by teddyzeenny** [comment]
Can you reproduce this in an online app or jsbin?

**Comment by seansellek** [comment]
Hello, I'm also seeing this error and can reproduce it with this app: http://boundless-fog.surge.sh/

It is simply the getting started app. Stack trace is: 

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: inspect is not defined
Stack trace: ReferenceError: inspect is not defined
    at Class.inspectElement (<anonymous>:301:7)
    at Class.inspectElement (<anonymous>:3641:29)
    at Class.inspectElement (<anonymous>:3553:14)
    at Object.apply (http://boundless-fog.surge.sh/assets/vendor.js:32596:18)
    at Object.sendEvent (http://boundless-fog.surge.sh/assets/vendor.js:26062:28)
    at Class.trigger (http://boundless-fog.surge.sh/assets/vendor.js:44088:25)
    at <anonymous>:2799:16
    at Class.<anonymous> (<anonymous>:2829:18)
    at Object.run (http://boundless-fog.surge.sh/assets/vendor.js:10797:25)
    at run (http://boundless-fog.surge.sh/assets/vendor.js:30383:27)
```

**Comment by locks** [comment]
I can't reproduce @seansellek, works properly here :\ What's the version of your Inspector?

**Comment by rwwagner90** [comment]
This is not reproducible on latest Ember Inspector. Please update and the problem should go away.
