### ISSUE TITLE
Ember Inspector has errored - version(1.9.5)

### ISSUE THREAD

**Issue by Maruboinasuresh** [emberjs/ember-inspector#529]
DEBUG: -------------------------------
ember.debug.js:6395 DEBUG: Ember      : 2.4.4
ember.debug.js:6395 DEBUG: Ember Data : 2.4.3
ember.debug.js:6395 DEBUG: jQuery     : 1.11.3
ember.debug.js:6395DEBUG: -------------------------------
VM161:87 Ember Inspector Active

Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: _emberData.default.belognsTo is not a function
Stack trace: TypeError: _emberData.default.belognsTo is not a function
    at Module.callback (http://localhost:4200/assets/scripts/zohosurvey.js:405:43)
    at Module.exports (http://localhost:4200/assets/scripts/vendor.js:63:34)
    at Module.build (http://localhost:4200/assets/scripts/vendor.js:113:10)
    at findModule (http://localhost:4200/assets/scripts/vendor.js:161:9)
    at requireModule (http://localhost:4200/assets/scripts/vendor.js:148:12)
    at Ember.DefaultResolver.extend._extractDefaultExport (http://localhost:4200/assets/scripts/vendor.js:67459:20)
    at resolveOther (http://localhost:4200/assets/scripts/vendor.js:67191:32)
    at superWrapper (http://localhost:4200/assets/scripts/vendor.js:33758:22)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/scripts/vendor.js:16379:35)
    at resolve (http://localhost:4200/assets/scripts/vendor.js:12935:36)

**Comment by teddyzeenny** [comment]
You have a typo in your model file. Replace `belognsTo` with `belongsTo` :)

**Comment by Maruboinasuresh** [comment]
Great thank you :)
