### ISSUE TITLE
Error message: _emberData.default.atrr is not a function

### ISSUE THREAD

**Issue by flpms** [emberjs/ember-inspector#549]
My ember inspector run for while and after broken with the follow stack trace

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: _emberData.default.atrr is not a function
Stack trace: TypeError: _emberData.default.atrr is not a function
    at Module.callback (http://localhost:4200/assets/front-admin.js:1450:35)
    at Module.exports (http://localhost:4200/assets/vendor.js:93:34)
    at Module.build (http://localhost:4200/assets/vendor.js:145:10)
    at findModule (http://localhost:4200/assets/vendor.js:196:9)
    at requireModule (http://localhost:4200/assets/vendor.js:184:12)
    at _extractDefaultExport (http://localhost:4200/assets/vendor.js:83886:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:83621:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:33266:22)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15934:35)
    at resolve (http://localhost:4200/assets/vendor.js:12488:36)```

**Comment by teddyzeenny** [comment]
You have a typo in your applicaiton's code. In one of your models you wrote `DS.atrr` instead of `DS.attr`. The inspector thought that it caused the error because it was the first one that loaded that model's module.
