### ISSUE TITLE
Cannot inspect application controller

### ISSUE THREAD

**Issue by shhQuiet** [emberjs/ember-inspector#550]
I have no defined application controller, instead relying on the default.  However, in the inspector, under the "Controller" column I see `function Object() { [native code] }` and clicking it gives an error in the console:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Can't inspect [object Object]. Only Ember objects and arrays are supported.
Stack trace: Error: Can't inspect [object Object]. Only Ember objects and arrays are supported.
    at sendObject (<anonymous>:2271:15)
    at inspectById (<anonymous>:2199:14)
    at Object.apply (http://localhost:4200/assets/vendor.js:33404:18)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:26951:28)
    at exports.default._emberMetalMixin.Mixin.create.trigger (http://localhost:4200/assets/vendor.js:44783:25)
    at <anonymous>:2799:16
    at .<anonymous> (<anonymous>:2829:18)
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10781:25)
    at run (http://localhost:4200/assets/vendor.js:31242:27)
    at wrap (<anonymous>:2827:14)
```

If I click the $E and look at the object in the console, it is a class called `Child`

Other info:
```
DEBUG: -------------------------------
ember.debug.js:6440DEBUG: Ember      : 2.5.1
ember.debug.js:6440DEBUG: Ember Data : 2.5.2
ember.debug.js:6440DEBUG: jQuery     : 2.2.3
ember.debug.js:6440DEBUG: -------------------------------
VM10825:87Ember Inspector Active
```

**Comment by dhyan** [comment]
I have the same issue with ember-inspector 1.10.0 . This might get fixed soon but there is a possible work-around [here](https://github.com/emberjs/ember-inspector/issues/487)

**Comment by teddyzeenny** [comment]
Fixed in https://github.com/emberjs/ember-inspector/pull/563
