### ISSUE TITLE
Build failed / no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules

### ISSUE THREAD

**Issue by valk** [emberjs/ember-inspector#556]
Hi, I'm following the instructions and building for Chrome.

After executing ```npm run build``` and eventually:

```bash
ember build
```
I'm getting the following error:

```bash
> ember build
Future versions of Ember CLI will not support v5.9.1. Please update to Node 0.12 or io.js.
version: 0.2.0

A new version of ember-cli is available (2.6.1). To install it, type ember update.
invalid watchman found, version: [4.5.0] did not satisfy [^3.0.0], falling back to NodeWatcher
Build failed.
ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
Error: ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
  at Error (native)
  at Object.fs.readdirSync (fs.js:856:18)
  at /home/me/ember-inspector/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
  at Array.map (native)
  at mergeRelativePath (/home/me/ember-inspector/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
  at /home/me/ember-inspector/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
  at lib$rsvp$$internal$$tryCatch (/home/me/ember-inspector/node_modules/rsvp/dist/rsvp.js:1036:16)
  at lib$rsvp$$internal$$invokeCallback (/home/me/ember-inspector/node_modules/rsvp/dist/rsvp.js:1048:17)
  at lib$rsvp$$internal$$publish (/home/me/ember-inspector/node_modules/rsvp/dist/rsvp.js:1019:11)
  at lib$rsvp$asap$$flush (/home/me/ember-inspector/node_modules/rsvp/dist/rsvp.js:1198:9)
  at _combinedTickCallback (node.js:376:9)
  at process._tickCallback (node.js:407:11)
```

More info:

```bash
> ember -v
Future versions of Ember CLI will not support v5.9.1. Please update to Node 0.12 or io.js.
version: 0.2.0

A new version of ember-cli is available (2.6.1). To install it, type ember update.
invalid watchman found, version: [4.5.0] did not satisfy [^3.0.0], falling back to NodeWatcher
node: 5.9.1
npm: 2.7.0
```

**Comment by teddyzeenny** [comment]
I think node > 0.12 is not yet supported to build the inspector.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/ember-inspector/pull/563
