### ISSUE TITLE
Ember Inspector has errored.

### ISSUE THREAD

**Issue by ChillarAnand** [emberjs/ember-inspector#565]
```
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Pricing is not defined
Stack trace: ReferenceError: Pricing is not defined
    at http://127.0.0.1:4200/assets/irene.js:2692:24
    at mod.state (http://127.0.0.1:4200/assets/vendor.js:150:29)
    at tryFinally (http://127.0.0.1:4200/assets/vendor.js:30:14)
    at requireModule (http://127.0.0.1:4200/assets/vendor.js:148:5)
    at Class._extractDefaultExport (http://127.0.0.1:4200/assets/vendor.js:59200:20)
    at Class.resolveOther (http://127.0.0.1:4200/assets/vendor.js:58932:32)
    at Class.superWrapper (http://127.0.0.1:4200/assets/vendor.js:27005:20)
    at Class.resolve (http://127.0.0.1:4200/assets/vendor.js:14318:35)
    at Object.resolve [as resolver] (http://127.0.0.1:4200/assets/vendor.js:14081:23)
    at resolve (http://127.0.0.1:4200/assets/vendor.js:11656:29)
    at Object.resolve (http://127.0.0.1:4200/assets/vendor.js:11200:21)
    at factoryFor (http://127.0.0.1:4200/assets/vendor.js:10764:28)
```

**Comment by teddyzeenny** [comment]
That is likely an error in your app but triggered by the inspector when it imported a faulty module.
Did you see this when you opened the routes tab or data tab?

**Comment by ChillarAnand** [comment]
When I opened data tab. Looks like there was something wrong with app itself. Thanks.
