### ISSUE TITLE
Error reading watchModelTypes without Ember Data

### ISSUE THREAD

**Issue by krukid** [emberjs/ember-inspector#569]
I've removed `ember-data` from my project and started getting the following error in the console:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'watchModelTypes' of undefined
Stack trace: TypeError: Cannot read property 'watchModelTypes' of undefined
    at Class.getModelTypes (<anonymous>:844:54)
    at Object.sendEvent (http://admin.mint.local:7000/assets/vendor.js:26376:18)
    at Class.trigger (http://admin.mint.local:7000/assets/vendor.js:44030:25)
    at <anonymous>:2799:16
    at Class.<anonymous> (<anonymous>:2829:18)
    at Object.run (http://admin.mint.local:7000/assets/vendor.js:10422:25)
    at run (http://admin.mint.local:7000/assets/vendor.js:30699:27)
    at Class.wrap (<anonymous>:2827:14)
    at Class.messageReceived (<anonymous>:2798:12)
    at <anonymous>:2790:17
```

Currently I have no models in my project.
Ember Inspector v1.10.0

**Comment by teddyzeenny** [comment]
The only reason I can think of this could happen is because you visited the Data tab in the inspector, removed Ember Data from your project, and refreshed the page. Is this what happened @krukid . Can you try closing and reopening devtools?

**Comment by krukid** [comment]
yes, reopening the app in another tab fixed things, thanks!
