### ISSUE TITLE
Ember Inspector not working in my app

### ISSUE THREAD

**Issue by GopinathJanakiraman** [emberjs/ember-inspector#615]
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: attr is not defined
Stack trace: ReferenceError: attr is not defined
    at Module.callback (http://localhost:4200//assets/vendor.js:133627:18)
    at Module.exports (http://localhost:4200//assets/vendor.js:132:32)
    at Module.reify (http://localhost:4200//assets/vendor.js:153:59)
    at Module.exports (http://localhost:4200//assets/vendor.js:130:10)
    at requireModule (http://localhost:4200//assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4200//assets/vendor.js:195235:20)
    at Class.resolveOther (http://localhost:4200//assets/vendor.js:194948:32)
    at Class.superWrapper (http://localhost:4200//assets/vendor.js:35884:22)
    at Class.resolve (http://localhost:4200//assets/vendor.js:17197:35)
    at resolve (http://localhost:4200//assets/vendor.js:13529:36)

I use 
Ember      : 2.8.2
Ember Data : 2.9.0
jQuery     : 3.1.1

**Comment by teddyzeenny** [comment]
I think you forgot to either do `DS.attr` or `const { attr } = DS`. Please check your model files.

**Comment by GopinathJanakiraman** [comment]
where ever I am using , Its there teddy `const { Model, attr,  hasMany} = DS;`

**Comment by locks** [comment]
Do you also have `import DS from 'ember-data';`?
