### ISSUE TITLE
TypeError: Cannot read property 'firstNode' of undefined

### ISSUE THREAD

**Issue by ryanrishi** [emberjs/ember-inspector#630]
Could be similar to #373 ...this happened when I was inspecting the view tree and checked the "components".

Ember v2.9.1
Ember Inspector v2.0.4
Ember Data v2.8.1

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'firstNode' of undefined
Stack trace: TypeError: Cannot read property 'firstNode' of undefined
    at Class._highlightNode (<anonymous>:5239:38)
    at Class.previewLayer (<anonymous>:4433:18)
    at Object.sendEvent (http://XXX.localhost.XXX.com:2501/assets/vendor.js:33846:18)
    at Class.trigger (http://XXX.localhost.XXX.com:2501/assets/vendor.js:50156:25)
    at <anonymous>:3603:16
    at Class.<anonymous> (<anonymous>:3633:18)
    at Backburner.run (http://XXX.localhost.XXX.com:2501/assets/vendor.js:14723:25)
    at run (http://XXX.localhost.XXX.com:2501/assets/vendor.js:38157:27)
    at Class.wrap (<anonymous>:3631:14)
    at Class.messageReceived (<anonymous>:3602:12)
```

**Comment by locks** [comment]
@ryanrishi hi, do you have a reproduction we can do to look into this?

**Comment by ryanrishi** [comment]
No, unfortunately I don't have steps to reproduce this—just normal ember development.

**Comment by rwwagner90** [comment]
Without steps to reproduce, I'm going to close this for now. Please feel free to reopen if you can help us out with a reproduction!
