### ISSUE TITLE
Error message: routeNames.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by titov-andrei** [emberjs/ember-inspector#634]
```
ember.debug.js:5987 DEBUG: -------------------------------
ember.debug.js:5987 DEBUG: Ember      : 2.12.0-beta.2
ember.debug.js:5987 DEBUG: Ember Data : 2.12.0-beta.4
ember.debug.js:5987 DEBUG: jQuery     : 3.1.1
ember.debug.js:5987 DEBUG: -------------------------------
VM184:83 Ember Inspector Active
VM184:96 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: routeNames.hasOwnProperty is not a function
Stack trace: TypeError: routeNames.hasOwnProperty is not a function
    at Class.<anonymous> (<anonymous>:4050:25)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:27913:28)
    at Object.get (http://localhost:4200/assets/vendor.js:32894:19)
    at Class.get (http://localhost:4200/assets/vendor.js:45602:26)
    at Class.sendTree (<anonymous>:4060:28)
    at Class.getTree (<anonymous>:4030:14)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:28784:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:44894:19)
    at <anonymous>:3603:16
    at Class.<anonymous> (<anonymous>:3633:18)
warn @ VM184:96
handleError @ VM184:153
(anonymous) @ VM184:3635
run @ ember.debug.js:718
run @ ember.debug.js:22663
wrap @ VM184:3631
messageReceived @ VM184:3602
(anonymous) @ VM184:3594
(anonymous) @ VM184:131
_messageReceived @ VM184:130
(anonymous) @ VM184:324
run @ ember.debug.js:718
run @ ember.debug.js:22663
(anonymous) @ VM184:323
```

**Comment by rwjblue** [comment]
In Ember@2.12.0-beta.2 and higher [router.router.recognizer.names](https://github.com/tildeio/route-recognizer/blob/b22f56762fe9e61eeacc0c5e2cb794a39dabb21f/lib/route-recognizer/util.ts#L2)  is an object with a null prototype (`Object.create(null)`), so calling `hasOwnProperty` [here](https://github.com/emberjs/ember-inspector/blob/de338013f374e97c70ac9860cdc0c51453fbaaa4/ember_debug/route-debug.js#L44) causes this error.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-inspector/pull/635 should address
