### ISSUE TITLE
Cannot read property 'class' of undefined

### ISSUE THREAD

**Issue by jakeleboeuf** [emberjs/ember-inspector#639]
Ember Version:
```
DEBUG: -------------------------------
DEBUG: Ember          : 2.12.0-beta.2
DEBUG: Ember Data : 2.12.0-beta.4
```

Console error:
```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'class' of undefined
Stack trace: TypeError: Cannot read property 'class' of undefined
    at Class._nameToClass (http://localhost:4200/assets/vendor.js:17944:62)
    at http://localhost:4200/assets/vendor.js:18142:25
    at Array.map (native)
    at Class.getModelTypes (http://localhost:4200/assets/vendor.js:18140:38)
    at Class.watchModelTypes (http://localhost:4200/assets/vendor.js:17918:29)
    at Class.getModelTypes (<anonymous>:821:55)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:29454:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:45564:19)
    at <anonymous>:3603:16
    at Class.<anonymous> (<anonymous>:3633:18)
```

vendor.js
```
_nameToClass: function (type) {
  if (typeof type === 'string') {
    var owner = _emberUtils.getOwner(this);
    type = owner[_container.FACTORY_FOR]('model:' + type).class; <---- LINE 17944 ----<<
  }
  return type;
},
```

**Comment by rwjblue** [comment]
Fixed in ember upstream in https://github.com/emberjs/ember.js/pull/14969. Will be included in 2.12.0 final when released.
