### ISSUE TITLE
You may not set `id` as an attribute on your model.

### ISSUE THREAD

**Issue by nijikokun** [emberjs/ember-inspector#653]
Whenever I create a custom `RESTSerializer` to format a non-standard API request to validate with `RESTAdapter` / `Serializer` I get the following issue **only inside of ember-inspector** and cannot use ember-inspector at all:

```
Error message: Assertion Failed: You may not set `id` as an attribute on your model. Please remove any lines that look like: `id: DS.attr('<type>')` from (unknown mixin)
Stack trace: Error
    at assert (http://localhost:4200/assets/vendor.js:16561:13)
    at Object.assert (http://localhost:4200/assets/vendor.js:28312:34)
    at assert (http://localhost:4200/assets/vendor.js:73862:37)
    at Class.willMergeMixin (http://localhost:4200/assets/vendor.js:76982:41)
    at mergeMixins (http://localhost:4200/assets/vendor.js:31426:16)
    at mergeMixins (http://localhost:4200/assets/vendor.js:31444:9)
    at applyMixin (http://localhost:4200/assets/vendor.js:31549:5)
    at MixinPrototype.applyPartial (http://localhost:4200/assets/vendor.js:31810:12)
    at Function.proto (http://localhost:4200/assets/vendor.js:47191:32)
    at Object.validatePropertyInjections (http://localhost:4200/assets/vendor.js:42509:25)
```

**Note**: My model does **not** have any `id: attr('string')` on them in the code.

Here is the custom serializer at work:

```js
import DS from 'ember-data'

export default DS.RESTSerializer.extend({
  normalizeSingleResponse (store, primaryModelClass, payload, id, requestType) {
    payload.id = id // this is the line that breaks ember-inspector, removing it breaks the ember application.

    payload = {
      information: payload
    }

    return this._normalizeResponse(store, primaryModelClass, payload, id, requestType, true)
  }
})
```

Here are my ember details:

```
ember.debug.js:6008 DEBUG: Ember      : 2.12.1
ember.debug.js:6008 DEBUG: Ember Data : 2.12.2
ember.debug.js:6008 DEBUG: jQuery     : 3.2.1
```

**Comment by rwwagner90** [comment]
Can you just not set that `id`?

**Comment by rwwagner90** [comment]
Closing this for now, as setting the id manually is typically not done. We may revisit in the future.
