### ISSUE TITLE
Cannot access data pane on 2.0.6

### ISSUE THREAD

**Issue by mfeckie** [emberjs/ember-inspector#678]
On trying to access the data pane, I am unable to enter and get an error message:

```
VM66:96 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'set' of undefined
Stack trace: TypeError: Cannot read property 'set' of undefined
    at Class.<anonymous> (<anonymous>:680:14)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:43084:28)
    at get (http://localhost:4200/assets/vendor.js:42392:19)
    at Class.get (http://localhost:4200/assets/vendor.js:56415:34)
    at Class.checkAdapter (<anonymous>:814:61)
    at sendEvent (http://localhost:4200/assets/vendor.js:40160:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:55809:33)
    at <anonymous>:3609:16
    at Class.<anonymous> (<anonymous>:3639:18)
    at Backburner.run (http://localhost:4200/assets/vendor.js:26607:36)
```

The error seems to be happening somewhere around here:

```
ember-debug/port

    messageReceived: function messageReceived(name, message) {
      var _this2 = this;

      this.wrap(function () {
        _this2.trigger(name, message);
      });
    },
```

I've tried it with multiple applications and consistently get the error.

```
Ember Inspector	2.0.6
Ember	2.13.3
Ember Data	2.13.1
```

**Comment by rjschie** [comment]
Likewise, my data pane has been causing the browser tab to lock up and stop functioning. No errors that I can see, just unresponsive.

Ember Inspector: 2.0.6
Ember: 2.13.4
Ember Data 2.14.3

**Comment by mfeckie** [comment]
Interestingly I discovered that I had a 'rogue' module in the `models` folder which was causing the issue.
