### ISSUE TITLE
ember inspector error in Chrome Version 65.0.3325.181

### ISSUE THREAD

**Issue by rinoldsimon** [emberjs/ember-inspector#783]
An error has occurred when switching to `data` tab:
Chrome Version: `65.0.3325.181`

VM322:92 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: _emberInflector.default.uncountable is not a function
Stack trace: TypeError: _emberInflector.default.uncountable is not a function
    at Module.callback (https://medzbook.local/assets/medzbook-client.js:13598:27)
    at Module.exports (https://medzbook.local/assets/vendor.js:111:32)
    at requireModule (https://medzbook.local/assets/vendor.js:32:18)
    at Class._extractDefaultExport (https://medzbook.local/assets/vendor.js:91540:20)
    at Class.resolveOther (https://medzbook.local/assets/vendor.js:91258:32)
    at Class.superWrapper [as resolveOther] (https://medzbook.local/assets/vendor.js:60963:22)
    at Class.resolve (https://medzbook.local/assets/vendor.js:28839:35)
    at _resolve (https://medzbook.local/assets/vendor.js:26813:36)
    at Registry.resolve (https://medzbook.local/assets/vendor.js:26515:21)
    at Registry.resolve (https://medzbook.local/assets/vendor.js:26519:55)

**Comment by rinoldsimon** [comment]
can't access `data` tab in browsers including `firefox`.

**Comment by rwwagner90** [comment]
@rinoldsimon can you please give more info? What website are you trying to inspect? Ember versions, etc?

**Comment by rinoldsimon** [comment]
I'm inspecting my Ember app. `ember` version `2.18.2`, `ember-cli` version `2.18.2`

**Comment by rwwagner90** [comment]
@rinoldsimon can you please share some code or a link to a deployed site where we can reproduce the error?

**Comment by rinoldsimon** [comment]
steps to reproduce:
- install `Ember Inspector` browser extension in `chrome` or `firefox`
- run `ember server`
- click `data` under `ember` tab in `developer tool`

**Comment by rwwagner90** [comment]
@rinoldsimon the data tab works great for me. Can you please share some code or a link to a deployed site where we can reproduce the error?

**Comment by rinoldsimon** [comment]
I'm running the ember app in my local machine

**Comment by rwwagner90** [comment]
Can you please share some code or a link to a deployed site where we can reproduce the error? Perhaps put together a reproduction repo on GitHub, if you do not have any code pushed we can look at?
