### ISSUE TITLE
Data tab showing nothing

### ISSUE THREAD

**Issue by fdimauro** [emberjs/ember-inspector#823]
When I click on the Data tab nothing happens. No data is shown.

**Comment by fdimauro** [comment]
Sorry I am unable to even click on the Data tab. The GUI will not let me.

**Comment by rwwagner90** [comment]
@fdimauro are you using engines? I'm pretty sure engines break the data tab. Without more info, we cannot help debug this. There are likely errors, if you could please share those.

**Comment by alexmiddeleer** [comment]
@rwwagner90 I am also seeing this, as of today. The data tab is unreachable. This is the error I see in the console.

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: (0 , _emberData.belongsTo) is not a function
Stack trace: TypeError: (0 , _emberData.belongsTo) is not a function
    at Module.callback (http://localhost:4201/assets/vendor.js:137231:55)
    at Module.exports (http://localhost:4201/assets/vendor.js:111:32)
    at Module._reify (http://localhost:4201/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4201/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4201/assets/vendor.js:109:10)
    at requireModule (http://localhost:4201/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4201/assets/vendor.js:106606:20)
    at Class.resolveOther (http://localhost:4201/assets/vendor.js:106327:32)
    at Class.superWrapper [as resolveOther] (http://localhost:4201/assets/vendor.js:62498:22)
    at Class.resolve (http://localhost:4201/assets/vendor.js:30402:35)
    at _resolve (http://localhost:4201/assets/vendor.js:28376:36)
    at Registry.resolve (http://localhost:4201/assets/vendor.js:28078:21)
    at Registry.resolve (http://localhost:4201/assets/vendor.js:28082:55)
    at Container.factoryFor (http://localhost:4201/assets/vendor.js:27645:121)
    at Class.factoryFor (http://localhost:4201/assets/vendor.js:54966:33)
    at Class._nameToClass (http://localhost:4201/assets/vendor.js:31914:29)
    at http://localhost:4201/assets/vendor.js:32125:25
    at Array.map (<anonymous>)
    at Class.getModelTypes (http://localhost:4201/assets/vendor.js:32123:43)
    at Class.watchModelTypes (http://localhost:4201/assets/vendor.js:31889:29)
    at Class.getModelTypes (<anonymous>:683:55)
    at sendEvent (http://localhost:4201/assets/vendor.js:39769:18)
    at Class.trigger (http://localhost:4201/assets/vendor.js:55765:33)
    at wrap (<anonymous>:3476:14)
    at Class.<anonymous> (<anonymous>:3506:18)
    at Backburner._run (http://localhost:4201/assets/vendor.js:27359:35)
    at Backburner.run (http://localhost:4201/assets/vendor.js:27082:25)
    at run (http://localhost:4201/assets/vendor.js:43786:29)
    at Class.wrap (<anonymous>:3504:14)
    at Class.messageReceived (<anonymous>:3475:12)
    at get.onMessageReceived.message (<anonymous>:3469:16)
    at get.forEach.callback (<anonymous>:127:9)
    at Array.forEach (<anonymous>)
    at Class._messageReceived (<anonymous>:126:37)
    at run (<anonymous>:344:16)
    at Backburner._run (http://localhost:4201/assets/vendor.js:27359:35)
    at Backburner.run (http://localhost:4201/assets/vendor.js:27082:25)
    at run (http://localhost:4201/assets/vendor.js:43786:29)
    at MessagePort.chromePort.addEventListener.event (<anonymous>:343:9)
```

**Comment by ehubbell** [comment]
I'm experiencing a similar issue. Data tab was working fine for me the last several days then suddenly I can't click into view more details about each data model. I still get the index of records in the store for each model but I can't get the details pane to open. The error message doesn't offer much context:

```Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'eachAttribute' of undefined
Stack trace: TypeError: Cannot read property 'eachAttribute' of undefined
    at _debugInfo (http://localhost:4200/assets/vendor.js:171026:10)
    at getDebugInfo (<anonymous>:3359:19)
    at Class.mixinsForObject (<anonymous>:2993:23)
    at Class.sendObject (<anonymous>:2885:26)
    at Class.inspectModel (<anonymous>:721:37)
    at sendEvent (http://localhost:4200/assets/vendor.js:39473:14)
    at Class.trigger (http://localhost:4200/assets/vendor.js:54492:33)
    at wrap (<anonymous>:3461:14)
    at Class.<anonymous> (<anonymous>:3491:18)
    at Backburner._run (http://localhost:4200/assets/vendor.js:26637:35)```

**Comment by rwwagner90** [comment]
@ehubbell we've had several issues reported from the `eachAttribute` issue already. Please update to 3.3.1 that we just released and it will be fixed.

**Comment by ehubbell** [comment]
My B @rwwagner90. Working again!

**Comment by rwwagner90** [comment]
@drewda can you provide more info on your app please? I've found this is typically related to engines. I've also found sometimes clicking data 3-5 times makes it decide to actually go to the data tab.

**Comment by drewda** [comment]
@rwwagner90 this app isn't using engines.

I just found how to open a console to debug the extension and found the culprit: an error in one of the app's models. This wasn't in any currently active user flows, so I didn't think to check app code.

Thanks for your quick response.
