### ISSUE TITLE
Ember.copy deprecation warnings

### ISSUE THREAD

**Issue by bgentry** [emberjs/ember-inspector#834]
Using the ember-inspector on my v3.3 app spews an endless series of `Ember.copy` deprecation warnings:

```
15:00:44.656 telemetry.js:357 DEPRECATION: Use ember-copy addon instead of copy method and Copyable mixin. [deprecation id: ember-runtime.deprecate-copy-copyable] See https://emberjs.com/deprecations/v3.x/#toc_ember-runtime-deprecate-copy-copyable for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:17354:29)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17456:17)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:17378:17)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:17456:17)
        at invoke (http://localhost:4200/assets/vendor.js:17465:17)
        at deprecate (http://localhost:4200/assets/vendor.js:17437:34)
        at copy (http://localhost:4200/assets/vendor.js:52794:47)
        at Class.updateOrCreate (<anonymous>:1978:22)
        at Class.fulfill (<anonymous>:1992:26)
```

#### Screenshot

<img width="1347" alt="screen shot 2018-07-24 at 3 00 49 pm" src="https://user-images.githubusercontent.com/114033/43168525-7d21fdc4-8f52-11e8-9e62-7acd9b60ba9b.png">

Might be as simple as just changing to import for [this line](https://github.com/emberjs/ember-inspector/blob/1c34df9e8e7f521b380d09d6f7d3af15c650cc78/ember_debug/libs/promise-assembler.js#L98) to use ember-copy?

**Comment by bgentry** [comment]
Hopefully #835 is a suitable fix! :pray:
