### ISSUE TITLE
CI test failures on master

### ISSUE THREAD

**Issue by bgentry** [emberjs/ember-inspector#836]
There are a handful of failing tests on `master`, which can be seen in [the build](https://travis-ci.org/emberjs/ember-inspector/builds/407824073?utm_source=github_status&utm_medium=notification) for #835. These failures occur on `ember-release`, `ember-beta`, and `ember-canary` scenarios:

<details>

```
not ok 8 Chrome 68.0 - Ember Debug - Object Inspector: An Ember Object is correctly transformed into an inspection hash
    ---
        actual: >
            "My Object"
        expected: >
            My Object
        stack: >
                at Object.<anonymous> (http://localhost:7357/testing/assets/tests.js:6032:14)
                at runTest (http://localhost:7357/testing/assets/test-support.js:4055:30)
                at Test.run (http://localhost:7357/testing/assets/test-support.js:4041:6)
                at http://localhost:7357/testing/assets/test-support.js:4262:12
                at advanceTaskQueue (http://localhost:7357/testing/assets/test-support.js:3654:6)
                at Object.advance (http://localhost:7357/testing/assets/test-support.js:3635:4)
        negative: >
            false
        Log: |
    ...
not ok 9 Chrome 68.0 - Ember Debug - Object Inspector: Computed properties are correctly calculated
    ---
        actual: >
            "Hello"
        expected: >
            Hello
        stack: >
                at Object.<anonymous> (http://localhost:7357/testing/assets/tests.js:6075:14)
                at runTest (http://localhost:7357/testing/assets/test-support.js:4055:30)
                at Test.run (http://localhost:7357/testing/assets/test-support.js:4041:6)
                at http://localhost:7357/testing/assets/test-support.js:4262:12
                at advanceTaskQueue (http://localhost:7357/testing/assets/test-support.js:3654:6)
                at Object.advance (http://localhost:7357/testing/assets/test-support.js:3635:4)
        negative: >
            false
        Log: |
    ...
not ok 10 Chrome 68.0 - Ember Debug - Object Inspector: Cached Computed properties are pre-calculated
    ---
        actual: >
            "Hello"
        expected: >
            Hello
        stack: >
                at Object.<anonymous> (http://localhost:7357/testing/assets/tests.js:6098:14)
                at runTest (http://localhost:7357/testing/assets/test-support.js:4055:30)
                at Test.run (http://localhost:7357/testing/assets/test-support.js:4041:6)
                at http://localhost:7357/testing/assets/test-support.js:4262:12
                at advanceTaskQueue (http://localhost:7357/testing/assets/test-support.js:3654:6)
                at Object.advance (http://localhost:7357/testing/assets/test-support.js:3635:4)
        negative: >
            false
        Log: |
    ...
not ok 11 Chrome 68.0 - Ember Debug - Object Inspector: Properties are correctly bound
    ---
        actual: >
            "Alex"
        expected: >
            Alex
        stack: >
                at Object.<anonymous> (http://localhost:7357/testing/assets/tests.js:6135:14)
                at runTest (http://localhost:7357/testing/assets/test-support.js:4055:30)
                at Test.run (http://localhost:7357/testing/assets/test-support.js:4041:6)
                at http://localhost:7357/testing/assets/test-support.js:4262:12
                at advanceTaskQueue (http://localhost:7357/testing/assets/test-support.js:3654:6)
                at Object.advance (http://localhost:7357/testing/assets/test-support.js:3635:4)
        negative: >
            false
        Log: |
    ...
not ok 12 Chrome 68.0 - Ember Debug - Object Inspector: Properties can be updated through a port message
    ---
        actual: >
            "Alex"
        expected: >
            Alex
        stack: >
                at Object.<anonymous> (http://localhost:7357/testing/assets/tests.js:6184:14)
                at runTest (http://localhost:7357/testing/assets/test-support.js:4055:30)
                at Test.run (http://localhost:7357/testing/assets/test-support.js:4041:6)
                at http://localhost:7357/testing/assets/test-support.js:4262:12
                at advanceTaskQueue (http://localhost:7357/testing/assets/test-support.js:3654:6)
                at Object.advance (http://localhost:7357/testing/assets/test-support.js:3635:4)
        negative: >
            false
        Log: |
    ...
```

</details>

I was able to reproduce these failures locally on the `ember-release` track using this command:

```
$ ember try:one "ember-release" --skip-cleanup=true --- node_modules/.bin/ember test --filter="Ember Debug"
```

**Comment by rwwagner90** [comment]
Yes, we know about these failures. There were changes in Ember we have not fixed things for yet.
