### ISSUE TITLE
Problem resolving associated promise models in ember inspector 3.3.1

### ISSUE THREAD

**Issue by nolman** [emberjs/ember-inspector#856]
The model click in works now post 3.3.1 however if you try to resolve an association that is a promise in the inspector you get the following:

```
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: this.eachAttribute is not a function
Stack trace: TypeError: this.eachAttribute is not a function
    at Proxy._debugInfo (/assets/vendor.js:157311:10)
    at getDebugInfo (<anonymous>:3360:47)
    at Class.mixinsForObject (<anonymous>:2993:23)
    at Class.digIntoObject (<anonymous>:2869:28)
    at Class.digDeeper (<anonymous>:2760:14)
    at sendEvent (/assets/vendor.js:45855:14)
    at Class.trigger (/assets/vendor.js:61035:33)
    at wrap (<anonymous>:3462:14)
    at Class.<anonymous> (<anonymous>:3492:18)
    at Backburner._run (/assets/vendor.js:33021:35)
```

https://github.com/emberjs/ember-inspector/commit/194a035e2ebc43deb87a3b96321b08e3457025f3

**Comment by rwwagner90** [comment]
@nolman can you please tell me what you mean here and provide a way for me to reproduce this?

**Comment by nolman** [comment]
@rwwagner90 ![http://recordit.co/QT22u3nK9h.gif](http://recordit.co/QT22u3nK9h.gif)

**Comment by nolman** [comment]
@rwwagner90 I think if you click any belongsTo association or hasMany this will happen, I could be mistaken however and it could require a certain async setup with ember data.

**Comment by rwwagner90** [comment]
@nolman can you please provide a reproduction of some sort? That way, I can debug on all the same versions of everything you are using.

**Comment by dmtask** [comment]
I have the same Problem like @nolman.

**Comment by nolman** [comment]
Seeing this on the same versions as @dmtask (minus jquery)

**Comment by rwwagner90** [comment]
@nolman @dmtask I still need a reproduction of some sort please. Do either of you have some code you could share or better yet, a running app I could just inspect?

**Comment by nolman** [comment]
@rwwagner90 https://www.mymoji.co (try clicking from page -> app)

**Comment by rwwagner90** [comment]
Perfect, thanks for providing this @nolman! I will debug this after work today.

**Comment by thorsteinsson** [comment]
The error happens in ember-data at: https://github.com/emberjs/data/blob/bd74157c978f3d94799c06ca5812ae35d77a81d9/addon/-private/system/model/model.js#L1005
