### ISSUE TITLE
Error on test page

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember-inspector#878]
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'name' of undefined
Stack trace: TypeError: Cannot read property 'name' of undefined
    at Class.getRecords (<anonymous>:701:29)
    at sendEvent (http://localhost:4300/assets/vendor.js:38269:14)
    at Class.trigger (http://localhost:4300/assets/vendor.js:53447:33)
    at wrap (<anonymous>:3461:14)
    at Class.<anonymous> (<anonymous>:3491:18)
    at Backburner._run (http://localhost:4300/assets/vendor.js:25440:35)
    at Backburner.run (http://localhost:4300/assets/vendor.js:25150:25)
    at run (http://localhost:4300/assets/vendor.js:38431:29)
    at Class.wrap (<anonymous>:3489:14)
    at Class.messageReceived (<anonymous>:3460:12)

**Comment by rwwagner90** [comment]
@lifeart can you give us some more info please? What were you doing that caused the error?

**Comment by rwwagner90** [comment]
@lifeart do you have more info for us?

**Comment by lifeart** [comment]
@rwwagner90  cannot reproduce it( 
Have this error, using `ember-cli-hot-loader` in `/tests` page
