### ISSUE TITLE
Ember inspector crashes in Data tab

### ISSUE THREAD

**Issue by calexdiaz143** [emberjs/ember-inspector#946]
Issue came up after we updated our codebase to Node 10.10.0. Any ideas on what could be causing this? Tried a bit of debugging on my own but didn't get any insight.

VM563:100 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: entries.hasOwnProperty is not a function
Stack trace: TypeError: entries.hasOwnProperty is not a function
    at Class.catalogEntriesByType (http://localhost:4300/assets/vendor.js:65167:20)
    at Class.getModelTypes (http://localhost:4300/assets/vendor.js:16855:39)
    at Class.watchModelTypes (http://localhost:4300/assets/vendor.js:16641:29)
    at Class.getModelTypes (<anonymous>:809:55)
    at Object.apply (http://localhost:4300/assets/vendor.js:32459:18)
    at Object.sendEvent (http://localhost:4300/assets/vendor.js:26288:28)
    at Class.trigger (http://localhost:4300/assets/vendor.js:43062:25)
    at <anonymous>:2764:16
    at Class.<anonymous> (<anonymous>:2794:18)
    at Backburner.run (http://localhost:4300/assets/vendor.js:10991:25)

warn	@	VM563:100
handleError	@	VM563:157
(anonymous)	@	VM563:2796
run	@	ember.debug.js:294
run	@	ember.debug.js:19661
wrap	@	VM563:2792
messageReceived	@	VM563:2763
(anonymous)	@	VM563:2755
(anonymous)	@	VM563:135
_messageReceived	@	VM563:134
(anonymous)	@	VM563:359
run	@	ember.debug.js:294
run	@	ember.debug.js:19661
(anonymous)	@	VM563:358

**Comment by rwwagner90** [comment]
Do you have a reproduction we could look at?

**Comment by calexdiaz143** [comment]
No but found a solution by updating our codebase to Ember 3.
